### PR TITLE
added support for Regions

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please also change verison in package.json :-)
https://travis-ci.org/ioBroker/ioBroker.owntracks/jobs/450970278#L1388

**Comment by Zefau** [comment]
Changed now and build test passed successfully (luckily :-D)

**Comment by Apollon77** [comment]
Super. You have tested it?

**Comment by Zefau** [comment]
Testing it daily in my environment and also requested in the forum. Works well for me.

**Comment by Apollon77** [comment]
published to npm, in latest repo by tomorrow

**Pull request merged**
