### PR TITLE
Added support for Compact mode

### PR DESCRIPTION
**Pull request by Zefau**

### CODE REVIEW

**Comment by Zefau** [comment]
@GermanBluefox please merge, thanks

**Comment by Apollon77** [comment]
Can you please solve the conflict?

**Comment by Zefau** [comment]
I think the conflicts are caused by the incorrect io-package.json in the current repository.

**Comment by Zefau** [comment]
Alternatively, restore the io-package.json and I can resolve any conflicts on that one.

**Comment by Zefau** [comment]
I will rework the PR

**Pull request closed without merging**
